<h1 style="color:brown" align="center"> <b>Pandas: Introduction </b></h1>

# **Introduction to Pandas**
* **It is often said that 80% of data analysis activity is spent on the data cleaning and preparation of our data. To get the grip over this activity, this section will focus on a small but important aspect of data manipulation and cleaning with Pandas.**

## **Inbuilt Data Structure in Pandas**
**There are two types of data structures are there in Pandas -** <br>

* **Series -** It is one-dimensional labeled array capable of holding any data type (integer, string, float, Python objects etc.) of data. The axis is collectively referred to as index. <br>

* **Data Frame -** It is a two-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL Table or a Series of objects <br>

## **Series Data Structure**
**pandas.core.series.Series(data, index, dtype, copy)** <br>
* **data -** data takes various forms like ndarray, list, constants, dictionary etc. <br>
* **index -** it is unique and hashable for easy identification. <br>
* **dtype -** it is for data type. <br>
* **copy -** copy data, and its default value is False. It only affects for Series or one dimensional ndarray inputs. <br>

In [29]:
# !pip install numpy
# !pip install pandas

In [30]:
# importing required modules
import numpy as np
import pandas as pd

In [31]:
# creating empty series
s = pd.Series()
print(s, type(s))

Series([], dtype: object) <class 'pandas.core.series.Series'>

In [32]:
# to ignore warning messages (optional)
import warnings
warnings.filterwarnings('ignore')

In [33]:
# creating series from ndarray
arr_data = np.array(['apple', 'banana', 'pineapple', 'coconut'])
s = pd.Series(data = arr_data)
print(s)
print(type(s))
print(s[0], s[3])
print(s[1:3])

0        apple
1       banana
2    pineapple
3      coconut
dtype: object
<class 'pandas.core.series.Series'>
apple coconut
1       banana
2    pineapple
dtype: object

In [34]:
# creating series from ndarray
arr_data = np.array(['apple', 'banana', 'pineapple', 'coconut'])
my_index = ['fruit-1', 'fruit-2', 'fruit-3', 'fruit-4']
s = pd.Series(data = arr_data, index = my_index)
print(s)
print(type(s))
print(s['fruit-1'], s[0], s['fruit-3'], s[2])
s[0] = 'orange'
s['fruit-3'] = "guava"
print(s)

fruit-1        apple
fruit-2       banana
fruit-3    pineapple
fruit-4      coconut
dtype: object
<class 'pandas.core.series.Series'>
apple apple pineapple pineapple
fruit-1     orange
fruit-2     banana
fruit-3      guava
fruit-4    coconut
dtype: object

In [35]:
arr_data = np.array([100, 200, 300, 400])
s = pd.Series(arr_data, copy = False)
s[0] = 999; arr_data[2] = 888
print(arr_data)
print(s)

[999 200 888 400]
0    999
1    200
2    888
3    400
dtype: int32

In [36]:
arr_data = np.array([100, 200, 300, 400])
s = pd.Series(arr_data, copy = True)
s[0] = 999; arr_data[2] = 888
print(arr_data)
print(s)

[100 200 888 400]
0    999
1    200
2    300
3    400
dtype: int32

In [37]:
# creating series from ndarray
arr_data = np.array(['apple', 'banana', 'pineapple', 'coconut'])
my_index = ['fruit-1', 'fruit-2', 'fruit-1', 'fruit-2']
s = pd.Series(data = arr_data, index = my_index)
print(s)
print(type(s))
print(s['fruit-1'])
print(s['fruit-2'])

fruit-1        apple
fruit-2       banana
fruit-1    pineapple
fruit-2      coconut
dtype: object
<class 'pandas.core.series.Series'>
fruit-1        apple
fruit-1    pineapple
dtype: object
fruit-2     banana
fruit-2    coconut
dtype: object

In [38]:
# creating series from dictionary
dict_data = {'apple':100, 'banana':230, 'kiwi':450, 'lemon':345}
print(dict_data)
s = pd.Series(dict_data)
print(s)
s = pd.Series(dict_data, index = ['banana', 'apple', 'kiwi', 'lime', 'coconut'])
print(s)

{'apple': 100, 'banana': 230, 'kiwi': 450, 'lemon': 345}
apple     100
banana    230
kiwi      450
lemon     345
dtype: int64
banana     230.0
apple      100.0
kiwi       450.0
lime         NaN
coconut      NaN
dtype: float64

In [39]:
# creating series from a scalar
s = pd.Series(500, index = [100, 104, 102, 106])
print(s)

100    500
104    500
102    500
106    500
dtype: int64

In [40]:
# create series from a list
s = pd.Series(data = [100, 300, 200, 400], index = ['red', 'green', 'blue', 'black'])
print(s)

red      100
green    300
blue     200
black    400
dtype: int64

## DataFrame Data Structure

### Create DataFrame

In [41]:
user_data = [['alice',19,'F','student'],['john',26,'M','student']]
user_columns = ['name', 'age', 'gender', 'job']
user1 = pd.DataFrame(data = user_data)
user1

       0   1  2        3
0  alice  19  F  student
1   john  26  M  student

In [42]:
user_data = [['alice',19,'F','student'],['john',26,'M','student']]
user_columns = ['name', 'age', 'gender', 'job']
user1 = pd.DataFrame(data = user_data, columns = user_columns)
user1

    name  age gender      job
0  alice   19      F  student
1   john   26      M  student

In [43]:
user_data = dict(name=['eric','paul'], age=[22,58], gender=['M','F'], job=['student','manager'])
print(user_data)
user2 = pd.DataFrame(data = user_data)
user2

{'name': ['eric', 'paul'], 'age': [22, 58], 'gender': ['M', 'F'], 'job': ['student', 'manager']}

   name  age gender      job
0  eric   22      M  student
1  paul   58      F  manager

In [44]:
user_data = {'name':['peter','julie'], 'age':[33,44], 'gender':['M','F'], 'job':['engineer','scientist']}
print(user_data)
user3 = pd.DataFrame(data = user_data)
user3

{'name': ['peter', 'julie'], 'age': [33, 44], 'gender': ['M', 'F'], 'job': ['engineer', 'scientist']}

    name  age gender        job
0  peter   33      M   engineer
1  julie   44      F  scientist